" enable python flakes
filetype plugin indent on 
filetype on

set expandtab
set tabstop=4
set tabpagemax=15 "only show 15 tabs 
syntax on
syntax enable

"i dont know highlight is what ?
"set showmode
set cursorline " highlight the current line
highlight clear SignColumn
highlight clear LineNr

"pydiction
let g:pydiction_menu_height = 3 
let g:pydiction_location = '~/.vim/pydiction/complete-dict' 

"ctrlp
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_map = '<c-o>'
let g:ctrlp_cmd = 'CtrlP'

map <c-b> :CtrlPBuffer<CR>

"let g:Powerline_symbols='fancy'
"set nu
"set linespace=0
set hlsearch
set autoindent
"set background=dark
"colorscheme black
let python_highlight_all = 1
" color
if $TERM =~ '^xterm' || $TERM =~ '^screen' || $TERM=~ '256color$'
        "set t_Co=256
        set background=dark
        let g:solarized_termcolors = 256
        let g:solarized_termtrans=1
        let g:solarized_visibility="normal"
        let g:solarized_contrast="normal"

        colorscheme solarized
elseif has('gui_running')
        set background=light
        let g:solarized_termcolors = 256
        colorscheme solarized
elseif $TERM =~ 'cons25'
        colorscheme default
endif
"let Tlist_Show_One_File = 1

"colorscheme solarized
map <F7> :NERDTreeToggle<CR>
map <F9> :TlistToggle<CR>

set tags=tags;
set autochdir
